"""добавил_autoincrement_для_id_в_responses

Revision ID: 6cd915e7e6fd
Revises: ad42e6a12d9c
Create Date: 2025-04-23 19:10:32.568967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd915e7e6fd'
down_revision = 'ad42e6a12d9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
