"""создание таблиц Users, Jobs, Responses

Revision ID: a211489fcc4d
Revises: e31beef93767
Create Date: 2025-04-17 12:45:04.176267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a211489fcc4d'
down_revision = 'e31beef93767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=False, comment='Название вакансии'))
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=False, comment='Описание вакансии'))
    op.add_column('jobs', sa.Column('salary_from', sa.Float(), nullable=True, comment='Минимальная зарплата'))
    op.add_column('jobs', sa.Column('salary_to', sa.Float(), nullable=True, comment='Максимальная зарплата'))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг активности вакансии'))
    op.add_column('jobs', sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Время создания вакансии'))
    op.add_column('responses', sa.Column('message', sa.Text(), nullable=False, comment='Сообщение отклика'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'message')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'salary_to')
    op.drop_column('jobs', 'salary_from')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
