"""изменил_float_на_DECIMAL_в_jobs

Revision ID: ad42e6a12d9c
Revises: a211489fcc4d
Create Date: 2025-04-23 18:29:39.810454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad42e6a12d9c'
down_revision = 'a211489fcc4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'salary_from',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='Минимальная зарплата',
               existing_nullable=True)
    op.alter_column('jobs', 'salary_to',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='Максимальная зарплата',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'salary_to',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Максимальная зарплата',
               existing_nullable=True)
    op.alter_column('jobs', 'salary_from',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Минимальная зарплата',
               existing_nullable=True)
    # ### end Alembic commands ###
